AGENT_TYPE = 'pendulum'
MODE = 'supervised'
# GRID_DIM_X x GRID_DIM_Y
GRID_DIM_X = 84
GRID_DIM_Y = 64

EXP_NAME = 'dummy'

BATCH_SIZE = 64
EPS_START = 1
EPS_END = 0.01
EPS_DECAY = 5000
GAMMA = 0.99
HIST_LENGTH = 1
OPTIM_LR = 0.0005
PATIENCE = 1
REPLAY_SIZE = 2000000
SUPERVISED_EPISODES = 100
TARGET_UPDATE_PERIOD = 5


# epsilon_specs = {
#     'EPS_START': 0.95,
#     'EPS_END': 0.01,
#     'EPS_DECAY': 80000}

agent_specs = {
    'AGENT_TYPE': AGENT_TYPE,
    'MODE': MODE,
    'GRID_DIM_X': GRID_DIM_X,
    'GRID_DIM_Y': GRID_DIM_Y,
    'EXP_NAME': EXP_NAME,
    'BATCH_SIZE': BATCH_SIZE,  # Standard 32
    'GAMMA': GAMMA,  # Standard 0.99
    'HIST_LENGTH': HIST_LENGTH,
    'OPTIM_LR': OPTIM_LR,  # Standard 0.001
    'PATIENCE': PATIENCE,  # Standard 5
    'REPLAY_SIZE': REPLAY_SIZE,
    'SUPERVISED_EPISODES': SUPERVISED_EPISODES,
    'TARGET_UPDATE_PERIOD': TARGET_UPDATE_PERIOD,   # Standard 5
    # 'EPSILON_FILE': epsilon_specs
    'EPS_START': EPS_START,
    'EPS_END': EPS_END,
    'EPS_DECAY': EPS_DECAY
}
