AGENT_TYPE = 'compass'
MODE = 'supervised'
# GRID_DIM_X x GRID_DIM_Y
GRID_DIM_X = 15
GRID_DIM_Y = 15

EXP_NAME = 'compass_diff'

BATCH_SIZE = 32
EPS_START = 0.95
EPS_END = 0.05
EPS_DECAY = 80000
GAMMA = 0.99
HIST_LENGTH = 1
OPTIM_LR = 0.0001
PATIENCE = 1
REPLAY_SIZE = 1000000
SUPERVISED_EPISODES = 100
MODEL_SAVE_PERIOD = 50
TARGET_UPDATE_PERIOD = 5


# epsilon_specs = {
#     'EPS_START': 0.95,
#     'EPS_END': 0.01,
#     'EPS_DECAY': 80000}

agent_specs = {
    'AGENT_TYPE': AGENT_TYPE,
    'MODE': MODE,
    'GRID_DIM_X': GRID_DIM_X,
    'GRID_DIM_Y': GRID_DIM_Y,
    'EXP_NAME': EXP_NAME,
    'BATCH_SIZE': BATCH_SIZE,  # Standard 32
    'GAMMA': GAMMA,  # Standard 0.99
    'HIST_LENGTH': HIST_LENGTH,
    'OPTIM_LR': OPTIM_LR,  # Standard 0.001
    'PATIENCE': PATIENCE,  # Standard 5
    'REPLAY_SIZE': REPLAY_SIZE,
    'SUPERVISED_EPISODES': SUPERVISED_EPISODES,
    'MODEL_SAVE_PERIOD': MODEL_SAVE_PERIOD,
    'TARGET_UPDATE_PERIOD': TARGET_UPDATE_PERIOD,   # Standard 5
    # 'EPSILON_FILE': epsilon_specs
    'EPS_START': EPS_START,
    'EPS_END': EPS_END,
    'EPS_DECAY': EPS_DECAY
}
